---
dmx:
  # where the input comes from
  # this is the DMX Spot Controller ID
  input: 
    universe: 1
    id: 20

  # where the spots are.. currently limited to 1 universe
  output:
    universe: 2
    
shows:
  default:
    fixtures:
      F-SR-PS:
        id: 257
        type: 36LED_PS
        x: 0
        y: 0
        z: 0

      # SR Board
      F-SR-S:
        id: 465
        type: Ralinto_Spot
        x: 2
        y: 0
        z: 0
      F-SR-1-P: 
        id: 127
        type: LED_Wash
        x: 2.3
        y: 0
        z: 0

      F-SC-1-P:
        id: 399
        type: LED_Wash
        x: 3.333
        y: 0 
        z: 0
      F-SC-2-P:
        id: 408
        type: LED_Wash
        x: 4.666
        y: 0
        z: 0
      F-SC-S:
        id: 185
        type: LED_Spot
        x: 4
        y: 0
        z: 0

      F-SL-1-P: 
        id: 109
        type: LED_Wash
        x: 2.3
        y: 0
        z: 0
      F-SL-S:
        id: 480
        type: Ralinto_Spot
        x: 2
        y: 0
        z: 0

      F-SL-PS:
        id: 495
        type: 36LED_PS

    fixture_groups:
      F-PS:
        - F-SR-PS
        - F-SL-PS

fixture_aspects:

fixture_profiles:
  36Led_PS:
    h-range: 540
    v-range: 265
    hx: 42
    vz: 32
  LED_Wash:
    h-range: 540
    v-range: 184
    # direction of x = 0 for h
    hx: 128
    # direction of x,y for v
    vz: 0
    channels:
     - h
     - v
     - intensity
     - red
     - green
     - blue
     - white
     - speed
     - function
    managed_attributes:
     - h
     - v
 
  LED_Spot:
    h-range: 540
    v-range: 190
    # direction of x = 0 for h
    hx: 45
    # direction of x,y for v
    vz: 15
    color_values:
      white: 0
      red: 15
      green: 25
      blue: 35
    channels:
     - h-coarse
     - h-fine
     - v-coarse
     - v-fine
     - movement_speed
     - intensity
     - strobe
     - color
     - gobo
     - function
    managed_attributes:
     - h-coarse
     - h-fine
     - v-coarse
     - v-fine
 
  Ralinto_Spot:
    h-range: 540
    v-range: 210
    h-rotation: cw
    # direction of x = 0 for h
    hx: 129
    # direction of x,y for v
    vz: 10
    color_values:
      white: 0
      red: 15
      green: 25
      blue: 35
    channels:
     - h-coarse
     - h-fine
     - v-coarse
     - v-fine
     - movement_speed
     - intensity
     - shutter
     - color
     - gobo
     - gobo_rotation
     - focus
     - prism
     - autoplay
     - autoxy
     - function
    managed_attributes:
     - h-coarse
     - h-fine
     - v-coarse
     - v-fine
 