---
dmx:
  # where the input comes from
  # this is the DMX Spot Controller ID
  input: 
    universe: 1
    id: 1

  # where the spots are.. currently limited to 1 universe
  output:
    universe: 2
    
shows:
  default:
    # list of fixtures in your show
    fixtures:
      SDL-RS:
        id: 465
        type: Ralinto_Spot
        x: 0
        y: .3
        z: 0
      SDL-RF: 
        id: 127
        type: LED_Wash
        x: .666
        y: .3
        z: 0
      SDC-RW:
        id: 399
        type: LED_Wash
        x: 3.333
        y: 0 
        z: 0
      SDC-CS:
        id: 4
        type: LED_Spot
        x: 4
        y: 0
        z: 0
      SDC-LW:
        id: 408
        type: LED_Wash
        x: 4.666
        y: 0
        z: 0

    fixture_groups:
      spots:
        - SDC-CS
        - SDL-RS
      washes:
        - SDC-LW
        - SDC-RW
        - SDL-RF
      all:
       - SDC-LW
       - SDC-CS
       - SDC-RW
       - SDL-RF
       - SDL-RS

fixture_profiles:
  LED_Wash:
    h-range: 540
    v-range: 184
    # direction of x = 0 for h
    hx: 128
    # direction of x,y for v
    vz: 0
    channels:
     - h
     - v
     - intensity
     - red
     - green
     - blue
     - white
     - speed
     - function
    managed_attributes:
     - h
     - v
 
  LED_Spot:
    h-range: 540
    v-range: 190
    # direction of x = 0 for h
    hx: 45
    # direction of x,y for v
    vz: 15
    color_values:
      white: 0
      red: 15
      green: 25
      blue: 35
    channels:
     - h-coarse
     - h-fine
     - v-coarse
     - v-fine
     - movement_speed
     - intensity
     - strobe
     - color
     - gobo
     - function
    managed_attributes:
     - h-coarse
     - h-fine
     - v-coarse
     - v-fine
 
  Ralinto_Spot:
    h-range: 540
    v-range: 210
    h-rotation: cw
    # direction of x = 0 for h
    hx: 129
    # direction of x,y for v
    vz: 10
    color_values:
      white: 0
      red: 15
      green: 25
      blue: 35
    channels:
     - h-coarse
     - h-fine
     - v-coarse
     - v-fine
     - movement_speed
     - intensity
     - shutter
     - color
     - gobo
     - gobo_rotation
     - focus
     - prism
     - autoplay
     - autoxy
     - function
    managed_attributes:
     - h-coarse
     - h-fine
     - v-coarse
     - v-fine
 