---
dmx:
  # where the input comes from
  # this is the DMX Spot Controller ID
  input: 
    universe: 1
    id: 20

  # where the spots are.. currently limited to 1 universe
  output:
    universe: 2

# how we manage the joystick
joystick:
  type: wireless
  id: 1
  deadzone: 4000 