---
shows:
  default:
    fixtures:
      F-SR-PS:
        id: 257
        profile: 36LED_PS
        x: 0
        y: 0
        z: 0
      # SR Board
      F-SR-S:
        id: 465
        profile: Ralinto_Spot
        x: 2
        y: 0
        z: 0
      F-SR-1-P: 
        id: 127
        profile: LED_Wash
        x: 2.3
        y: 0
        z: 0

      F-SC-1-P:
        id: 399
        profile: LED_Wash
        x: 3.333
        y: 0 
        z: 0
      F-SC-2-P:
        id: 408
        profile: LED_Wash
        x: 4.666
        y: 0
        z: 0
      F-SC-S:
        id: 185
        profile: LED_Spot
        x: 4
        y: 0
        z: 0

      F-SL-1-P: 
        id: 109
        profile: LED_Wash
        x: 2.3
        y: 0
        z: 0
      F-SL-S:
        id: 480
        profile: Ralinto_Spot
        x: 2
        y: 0
        z: 0

      F-SL-PS:
        id: 495
        profile: 36LED_PS
        x: 12 
        y: 0
        z: 0

    fixture_groups:
      F-PS:
        - F-SR-PS
        - F-SL-PS

    fixture_aspects:
      truss: hanging
      tree: hanging,reversed


